### ISSUE TITLE
[Feature Request] History Blacklist

### ISSUE THREAD

**Issue by Slugiish** [IlyaChichkov/LethalAutocompleteMod#10]
I'd love if there were a config option to add a blacklist of commands that I don't want to show up in my command history when I use the up arrow. My main use for this would be to filter out confirm and deny commands which always tend to bog up my history and make me have to hit up arrow more times that I would like to access commands that I actually want to send.

**Comment by IlyaChichkov** [comment]
Hey there, thank you for your feature request! I've added history blacklist that you suggested both with autocomplete commands blacklist in the latest mod update [v0.4.2](https://github.com/IlyaChichkov/LethalAutocompleteMod/tree/0.4.2). If you spot anything else or have more ideas, feel free to shout them out.
