### ISSUE TITLE
Commands not fully autocompleted

### ISSUE THREAD

**Issue by Kelkios** [IlyaChichkov/LethalAutocompleteMod#4]
Whenever you try to use commands like "view monitor", pressing tab while typing "vi" will autocomplete to "View", but will not autocomplete "View monitor".

As far as I know there is no variable for the command "View" so it makes no sense to only complete "View".

Please correct me if this is intended, if there are variables, or if there is a limitation on what you can autocomplete.

**Comment by IlyaChichkov** [comment]
Hey, Kelkios, thanks for paying attention to this and letting me know. I will try to fix this in the new update along with the auto-completion of the route, info, buy commands.

**Comment by IlyaChichkov** [comment]
I uploaded a new version of the mod (v0.4.0), that should fix this problem. Please let me know if you run into anymore issues.
