### ISSUE TITLE
Can't include config in modpack

### ISSUE THREAD

**Issue by hazzuk** [IlyaChichkov/LethalAutocompleteMod#6]
Hello, first off what an awesome mod. Autocomplete was the first thing I noticed missing when playing the game, so thank you for your great work!

---

Issue:
I can't include the config for this mod in my modpack. You're auto generating the 'Save Data Path' as part of the main config. But this is a local path on my pc. Including this config as is would prevent it from working for others in a modpack.

Solution:
I would recommend moving 'Save Data Path' to a second config file, which wouldn't be included in the modpack. This way the user auto generates their own local path as per usual.

**Comment by IlyaChichkov** [comment]
Hi there! Thanks a bunch for the kind words about the mod.

Regarding the issue — I realized what the problem is and it's really critical for the mod's usability within modpacks. I'll try to get this fixed as soon as I can.

Thanks for bringing this to my attention!

**Comment by IlyaChichkov** [comment]
Fixed, now data path by default is none, and it'll only be used if user set some path to it and this path exist. Thanks again for bringing this to my attention.
